on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read    
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run Terrascan
      id: terrascan
      # uses: tenable/terrascan-action@main
      uses: ghasctl/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        #iac_dir:
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:
        #webhook_token:

    - name: Check Status
      run: |
        pwd
        ls -l 
        # ls -l "${{ github.workspace }}/"
        tree -d ./
        # find ./ -name terrascan.sarif 

    - name: upload sarif file
      uses: actions/upload-artifact@v3
      with:
        name: terrascan.sarif
        path: ${{ github.workspace }}/terrascan.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
        category: my-analysis-tool